/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare class JsAdapter {
  constructor(dModel: number, numLayers: number, rank: number, alpha: number, ewcLambda: number, lr: number)
  learnTurn(input: Array<number>, target: Array<number>): number
  consolidate(): void
  forward(input: Array<number>, layer: number): Array<number>
  get turnCount(): number
  toBytes(): Array<number>
  static fromBytes(bytes: Array<number>, lr: number): JsAdapter
  get numLayers(): number
  get dModel(): number
}
